package songvote

// Song contains information about a single song.
type Song struct {
	ID      int    `json:"id"`       // generated by store
	Name    string `json:"name"`     // song nam
	Artist  string `json:"artist"`   // song artist
	LinkURL string `json:"link_url"` // link to YouTube, Spotify, etc.
}

// (Song).Equals returns whether names and artists of two Song objects are the same.
func (s Song) Equals(other Song) bool {
	return (s.Name == other.Name) && (s.Artist == other.Artist)
}
