package songvote

// Song contains information and methods about a single song.
type Song struct {
	ID      int64  `json:"id"`       // generated by store
	Name    string `json:"name"`     // song name
	Artist  string `json:"artist"`   // song artist
	LinkURL string `json:"link_url"` // link to YouTube, etc
	Votes   int    `json:"votes"`    // number of votes
	Vetoed  bool   `json:"vetoed"`   // song has been vetoed
}

// Songs contains a slice of Song objects.
type Songs []Song

// (Song).Equal returns whether names and artists of two Song objects are the same.
func (s Song) Equal(other Song) bool {
	return (s.Name == other.Name) && (s.Artist == other.Artist)
}
