package songvote

// User contains information and methods related to a user.
type User struct {
	ID       int64  `json:"id"`       // generated by the store
	Inactive bool   `json:"inactive"` // if the user is inactive
	Name     string `json:"name"`     // user's name
	Password string `json:"password"` // user's password
	Vetoes   int    `json:"vetoes"`   // vetoes remaining
}

// Users contains a slice of User objects.
type Users []User

// (User).Equal returns true if names match.
func (u User) Equal(other User) bool {
	return u.Name == other.Name
}
