package songvote

// Veto is a record of what Song was vetoed by what User.
type Veto struct {
	ID     int64 `json:"id"`   // generated by store
	SongID int64 `json:"song"` // ID of vetoed song
	UserID int64 `json:"user"` // ID of user that vetoed
}

type Vetoes []Veto
