package songvote

// Veto is a record of what Song was vetoed by what User.
type Veto struct {
	ID   int64 `json:"id"`   // generated by store
	Song Song  `json:"song"` // vetoed song
	User User  `json:"user"` // user that vetoed
}

type Vetoes []Veto
