package songvote

// Vote is a record of what Song was voted for by what User.
type Vote struct {
	ID   int64 `json:"id"`   // generated by store
	Song Song  `json:"song"` // song in question
	User User  `json:"user"` // user that voted
}

type Votes []Veto
