package songvote

// Vote is a record of what Song was voted for by what User.
type Vote struct {
	ID     int64 `json:"id"`   // generated by store
	SongID int64 `json:"song"` // ID of song voted on
	UserID int64 `json:"user"` // ID of user that voted
}

type Votes []Vote
